import type { SchoolEntry } from "@/types/schools";

export const schoolsDataset: SchoolEntry[] = [
  {
    id: "es-integrada-madrid",
    slug: "escuela-integrada-madrid",
    name: "Escuela Integrada Madrid",
    routeType: "integrated",
    country: "España",
    city: "Madrid",
    baseAirport: "LECU",
    atoName: "ATO Madrid Sur",
    shortDescription: "Ruta integrada intensiva con calendario por fases y financiación parcial.",
    dataStatus: "partial",
    lastUpdatedAt: "2026-04-15",
    dataConfidence: "medium",
    advertisedPriceEUR: 89500,
    flypathEstimatedRealCostEUR: 106000,
    depositOrEnrollmentFeeEUR: 7500,
    paymentScheduleSummary: "Depósito + 5 hitos semestrales vinculados a fases.",
    refundPolicySummary: "Parcial por horas no voladas y gastos administrativos.",
    contractAvailableBeforePayment: "partial",
    financingAvailable: "yes",
    mccJocIncluded: "yes",
    advancedUprtIncluded: "optional",
    examFeesIncluded: "no",
    skillTestsIncluded: "no",
    trainingMaterialsIncluded: "yes",
    accommodationIncluded: "optional",
    fleetSummary: "Monomotor + bimotor, flota mixta de entrenamiento.",
    aircraftAvailability: "medium",
    studentAircraftRatio: "5.2:1",
    instructorStudentRatio: "4.3:1",
    languageOfInstruction: "Español / Inglés técnico",
    programDurationMonths: 22,
    class1Requirement: "Recomendado antes de bloquear plaza.",
    jobSupportSummary: "Taller de CV, simulacros y bolsa de empleo propia.",
    employmentClaimsType: "clear_non_guaranteed",
    scores: {
      documentTransparency: 62,
      costClarity: 58,
      financialRisk: 61,
      commercialRisk: 44,
      operationalSolidity: 66,
      dataConfidenceScore: 57,
    },
    redFlags: ["Tasas y skill tests fuera del precio principal."],
    pendingData: ["Contrato completo previo a matrícula.", "Detalle de reembolso por escenarios."],
    keyQuestions: ["¿Qué conceptos exactos quedan fuera?", "¿Qué hitos activan pagos finales?"],
  },
  {
    id: "es-modular-valencia",
    slug: "centro-modular-valencia",
    name: "Centro Modular Valencia",
    routeType: "modular",
    country: "España",
    city: "Valencia",
    baseAirport: "LEVC",
    atoName: "ATO Levante",
    shortDescription: "Ruta modular flexible para compatibilizar trabajo y progresión por etapas.",
    dataStatus: "demo",
    lastUpdatedAt: "2026-04-10",
    dataConfidence: "low",
    advertisedPriceEUR: 54000,
    flypathEstimatedRealCostEUR: 73500,
    depositOrEnrollmentFeeEUR: 2500,
    paymentScheduleSummary: "Pago por módulo al inicio de cada bloque.",
    refundPolicySummary: "Sin política pública detallada en la web.",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "optional",
    advancedUprtIncluded: "optional",
    examFeesIncluded: "no",
    skillTestsIncluded: "no",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "no",
    fleetSummary: "Flota orientada a hour building y módulos IFR.",
    aircraftAvailability: "medium",
    languageOfInstruction: "Español",
    programDurationMonths: 30,
    class1Requirement: "Solicitado antes de CPL/IR.",
    jobSupportSummary: "Asesoría de carrera básica al finalizar fases avanzadas.",
    employmentClaimsType: "vague",
    scores: {
      documentTransparency: 41,
      costClarity: 38,
      financialRisk: 68,
      commercialRisk: 63,
      operationalSolidity: 54,
      dataConfidenceScore: 33,
    },
    redFlags: ["Brecha elevada entre precio anunciado y coste real estimado."],
    pendingData: ["Contrato antes de pagar.", "Calendario de pagos completo."],
    keyQuestions: ["¿Cuál es el coste final modular completo?", "¿Qué soporte ofrece en transición a aerolínea?"],
  },
  {
    id: "es-universidad-barcelona",
    slug: "universidad-aeronautica-barcelona",
    name: "Universidad Aeronáutica Barcelona",
    routeType: "university_plus_license",
    country: "España",
    city: "Barcelona",
    baseAirport: "LEBL",
    atoName: "ATO Mediterráneo",
    associatedUniversity: "Universidad Aeronáutica Barcelona",
    shortDescription: "Grado de aviación con itinerario de vuelo integrado con ATO asociada.",
    dataStatus: "partial",
    lastUpdatedAt: "2026-04-12",
    dataConfidence: "medium",
    advertisedPriceEUR: 42000,
    flypathEstimatedRealCostEUR: 118000,
    depositOrEnrollmentFeeEUR: 4200,
    paymentScheduleSummary: "Matrícula anual académica + fases de vuelo por bloques.",
    refundPolicySummary: "Académico y vuelo con reglas separadas.",
    contractAvailableBeforePayment: "partial",
    financingAvailable: "yes",
    mccJocIncluded: "optional",
    advancedUprtIncluded: "optional",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "yes",
    accommodationIncluded: "no",
    fleetSummary: "Fase práctica operada por ATO externa con base secundaria.",
    aircraftAvailability: "medium",
    studentAircraftRatio: "6.1:1",
    instructorStudentRatio: "4.8:1",
    languageOfInstruction: "Español / Inglés",
    programDurationMonths: 48,
    class1Requirement: "Recomendado antes del segundo curso.",
    jobSupportSummary: "Orientación de carrera universitaria + bolsa partner.",
    employmentClaimsType: "clear_non_guaranteed",
    scores: {
      documentTransparency: 55,
      costClarity: 46,
      financialRisk: 64,
      commercialRisk: 38,
      operationalSolidity: 59,
      dataConfidenceScore: 52,
    },
    redFlags: ["Costes académicos y de vuelo se comunican en canales distintos."],
    pendingData: ["Licencia exacta garantizada por itinerario.", "Escenarios si no se obtiene Class 1."],
    keyQuestions: ["¿Qué parte de vuelo está garantizada por plaza?", "¿Qué ocurre si se abandona la parte práctica?"],
    universityTrack: {
      universityName: "Universidad Aeronáutica Barcelona",
      degreeType: "Grado oficial",
      degreeName: "Grado en Gestión y Operaciones de Vuelo",
      academicDurationYears: 4,
      ects: 240,
      licenseIncludedMode: "Itinerario opcional con ATO asociada",
      actualLicenseOutcome: "ATPL frozen (según horas y módulos completados)",
      partnerAto: "ATO Mediterráneo",
      academicCostEUR: 42000,
      flightCostEUR: 76000,
      totalEstimatedCostEUR: 118000,
      class1FailurePolicy: "Continuidad académica posible; itinerario de vuelo se pausa o cancela.",
    },
  },
  {
    id: "es-integrada-sevilla",
    slug: "escuela-integrada-sevilla",
    name: "Escuela Integrada Sevilla",
    routeType: "integrated",
    country: "España",
    city: "Sevilla",
    baseAirport: "LEZL",
    atoName: "Andalucía Flight Academy",
    shortDescription: "Programa integrado orientado a cadencia alta con base principal en Andalucía.",
    dataStatus: "demo",
    lastUpdatedAt: "2026-03-30",
    dataConfidence: "low",
    advertisedPriceEUR: 84000,
    flypathEstimatedRealCostEUR: 101500,
    depositOrEnrollmentFeeEUR: 6500,
    paymentScheduleSummary: "Matrícula inicial + pagos trimestrales.",
    refundPolicySummary: "Resumen comercial sin condiciones completas.",
    contractAvailableBeforePayment: "no",
    financingAvailable: "unknown",
    mccJocIncluded: "yes",
    advancedUprtIncluded: "no",
    examFeesIncluded: "no",
    skillTestsIncluded: "no",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "optional",
    fleetSummary: "Flota de pistón con disponibilidad variable por temporada.",
    aircraftAvailability: "low",
    languageOfInstruction: "Español",
    programDurationMonths: 21,
    class1Requirement: "Solicitado al inicio de fase práctica.",
    jobSupportSummary: "Promoción de convenios sin detalle de alcance.",
    employmentClaimsType: "vague",
    scores: {
      documentTransparency: 36,
      costClarity: 43,
      financialRisk: 72,
      commercialRisk: 67,
      operationalSolidity: 45,
      dataConfidenceScore: 30,
    },
    redFlags: ["Contrato no disponible antes de pago inicial."],
    pendingData: ["Política de reembolso formal.", "Ratio alumno/avión."],
    keyQuestions: ["¿Qué ocurre con retrasos por disponibilidad de flota?", "¿Qué cobertura real tienen los convenios?"],
  },
  {
    id: "es-modular-bilbao",
    slug: "escuela-modular-bilbao",
    name: "Escuela Modular Bilbao",
    routeType: "modular",
    country: "España",
    city: "Bilbao",
    baseAirport: "LEBB",
    atoName: "North Modular ATO",
    shortDescription: "Ruta modular con teoría flexible y fase IFR en bloques intensivos.",
    dataStatus: "partial",
    lastUpdatedAt: "2026-04-08",
    dataConfidence: "medium",
    advertisedPriceEUR: 59500,
    flypathEstimatedRealCostEUR: 78200,
    depositOrEnrollmentFeeEUR: 3000,
    paymentScheduleSummary: "Pago por bloque y reservas de vuelo.",
    refundPolicySummary: "Cláusulas parciales compartidas por email.",
    contractAvailableBeforePayment: "partial",
    financingAvailable: "yes",
    mccJocIncluded: "no",
    advancedUprtIncluded: "optional",
    examFeesIncluded: "no",
    skillTestsIncluded: "no",
    trainingMaterialsIncluded: "yes",
    accommodationIncluded: "no",
    fleetSummary: "Flota de entrenamiento con refuerzo estacional.",
    aircraftAvailability: "medium",
    studentAircraftRatio: "5.8:1",
    languageOfInstruction: "Español / Inglés",
    programDurationMonths: 28,
    class1Requirement: "Antes de IR/CPL.",
    jobSupportSummary: "Mentorización de salida y red de antiguos alumnos.",
    employmentClaimsType: "none",
    scores: {
      documentTransparency: 57,
      costClarity: 52,
      financialRisk: 60,
      commercialRisk: 35,
      operationalSolidity: 58,
      dataConfidenceScore: 56,
    },
    redFlags: [],
    pendingData: ["Detalle contractual único para todos los módulos."],
    keyQuestions: ["¿Cuál es el coste típico por repeticiones?"],
  },
  {
    id: "es-universidad-valencia",
    slug: "universidad-grado-vuelo-valencia",
    name: "Universidad Vuelo Valencia",
    routeType: "university_plus_license",
    country: "España",
    city: "Valencia",
    baseAirport: "LEVC",
    atoName: "Valencia Partner ATO",
    associatedUniversity: "Universidad Vuelo Valencia",
    shortDescription: "Grado universitario con opción de licencia mediante centro adscrito.",
    dataStatus: "demo",
    lastUpdatedAt: "2026-03-21",
    dataConfidence: "low",
    advertisedPriceEUR: 36000,
    flypathEstimatedRealCostEUR: 112000,
    depositOrEnrollmentFeeEUR: 3000,
    paymentScheduleSummary: "Matrícula anual + pagos de vuelo externos.",
    refundPolicySummary: "Sin documento unificado académico/vuelo.",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "optional",
    advancedUprtIncluded: "optional",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "no",
    fleetSummary: "Parte práctica en ATO asociada con base compartida.",
    aircraftAvailability: "unknown",
    languageOfInstruction: "Español",
    programDurationMonths: 48,
    class1Requirement: "Recomendado en primer curso.",
    jobSupportSummary: "Orientación académica; empleabilidad de vuelo no detallada.",
    employmentClaimsType: "unknown",
    scores: {
      documentTransparency: 39,
      costClarity: 35,
      financialRisk: 70,
      commercialRisk: 49,
      operationalSolidity: 48,
      dataConfidenceScore: 28,
    },
    redFlags: ["Información pública incompleta sobre costes de vuelo."],
    pendingData: ["Qué licencia se obtiene exactamente.", "Política en caso de no obtener Class 1."],
    keyQuestions: ["¿Qué parte del itinerario es obligatoria para licencia?", "¿Qué costes no académicos faltan?"],
    universityTrack: {
      universityName: "Universidad Vuelo Valencia",
      degreeType: "Título propio",
      degreeName: "Dirección y Operaciones Aeronáuticas",
      academicDurationYears: 4,
      ects: 240,
      licenseIncludedMode: "Opcional mediante partner",
      actualLicenseOutcome: "Variable según módulos contratados",
      partnerAto: "Valencia Partner ATO",
      academicCostEUR: 36000,
      flightCostEUR: 76000,
      totalEstimatedCostEUR: 112000,
      class1FailurePolicy: "Se mantiene grado; itinerario de vuelo no garantizado.",
    },
  },
  {
    id: "es-modular-andalucia",
    slug: "escuela-modular-andalucia",
    name: "Escuela Modular Andalucía",
    routeType: "modular",
    country: "España",
    city: "Málaga",
    baseAirport: "LEMG",
    atoName: "Costa Sur ATO",
    shortDescription: "Propuesta modular orientada a progresión por fases y coste controlado.",
    dataStatus: "partial",
    lastUpdatedAt: "2026-04-02",
    dataConfidence: "medium",
    advertisedPriceEUR: 57500,
    flypathEstimatedRealCostEUR: 74200,
    depositOrEnrollmentFeeEUR: 2800,
    paymentScheduleSummary: "Pago por módulo con opción de fraccionamiento interno.",
    refundPolicySummary: "Reembolso parcial en conceptos no consumidos.",
    contractAvailableBeforePayment: "yes",
    financingAvailable: "yes",
    mccJocIncluded: "optional",
    advancedUprtIncluded: "optional",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "no",
    trainingMaterialsIncluded: "yes",
    accommodationIncluded: "optional",
    fleetSummary: "Flota monomotor moderna y acuerdos para bimotor.",
    aircraftAvailability: "high",
    studentAircraftRatio: "4.7:1",
    instructorStudentRatio: "3.9:1",
    languageOfInstruction: "Español / Inglés",
    programDurationMonths: 27,
    class1Requirement: "Antes de CPL.",
    jobSupportSummary: "Acompañamiento en fases finales y revisión de perfil.",
    employmentClaimsType: "none",
    scores: {
      documentTransparency: 69,
      costClarity: 63,
      financialRisk: 49,
      commercialRisk: 28,
      operationalSolidity: 71,
      dataConfidenceScore: 64,
    },
    redFlags: [],
    pendingData: ["Cobertura exacta de skill tests."],
    keyQuestions: ["¿Qué umbral de horas dispara costes extra?"],
  },
  {
    id: "es-integrada-zaragoza",
    slug: "centro-integrado-zaragoza",
    name: "Centro Integrado Zaragoza",
    routeType: "integrated",
    country: "España",
    city: "Zaragoza",
    baseAirport: "LEZG",
    atoName: "Ebro Aviation ATO",
    shortDescription: "Programa integrado orientado a cadencia media con base en Aragón.",
    dataStatus: "demo",
    lastUpdatedAt: "2026-03-25",
    dataConfidence: "low",
    advertisedPriceEUR: 86500,
    flypathEstimatedRealCostEUR: 104500,
    depositOrEnrollmentFeeEUR: 7000,
    paymentScheduleSummary: "Depósito + hitos por fase de teoría y vuelo.",
    refundPolicySummary: "No detallada públicamente.",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "yes",
    mccJocIncluded: "yes",
    advancedUprtIncluded: "no",
    examFeesIncluded: "no",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "optional",
    fleetSummary: "Flota mixta con rotación de disponibilidad.",
    aircraftAvailability: "medium",
    languageOfInstruction: "Español",
    programDurationMonths: 23,
    class1Requirement: "Antes de fase de vuelo principal.",
    jobSupportSummary: "Bolsa de empleo externa sin detalle de tasa de colocación.",
    employmentClaimsType: "vague",
    scores: {
      documentTransparency: 42,
      costClarity: 47,
      financialRisk: 66,
      commercialRisk: 58,
      operationalSolidity: 56,
      dataConfidenceScore: 32,
    },
    redFlags: ["Contrato no confirmado previo al depósito."],
    pendingData: ["Skill tests incluidos o no.", "Política de reembolso formal."],
    keyQuestions: ["¿Qué documentación contractual se firma antes del primer pago?"],
  },
  {
    id: "es-universidad-madrid",
    slug: "universidad-grado-piloto-madrid",
    name: "Universidad Piloto Madrid",
    routeType: "university_plus_license",
    country: "España",
    city: "Madrid",
    baseAirport: "LEMD",
    atoName: "Madrid Campus Flight Center",
    associatedUniversity: "Universidad Piloto Madrid",
    shortDescription: "Grado universitario con integración parcial de formación práctica.",
    dataStatus: "partial",
    lastUpdatedAt: "2026-04-18",
    dataConfidence: "medium",
    advertisedPriceEUR: 45000,
    flypathEstimatedRealCostEUR: 121000,
    depositOrEnrollmentFeeEUR: 3900,
    paymentScheduleSummary: "Coste académico anual + coste de vuelo por fases.",
    refundPolicySummary: "Académico claro; vuelo con anexos por separado.",
    contractAvailableBeforePayment: "partial",
    financingAvailable: "yes",
    mccJocIncluded: "optional",
    advancedUprtIncluded: "optional",
    examFeesIncluded: "no",
    skillTestsIncluded: "no",
    trainingMaterialsIncluded: "yes",
    accommodationIncluded: "no",
    fleetSummary: "Formación práctica en partner con cupos por cohorte.",
    aircraftAvailability: "medium",
    studentAircraftRatio: "6.4:1",
    instructorStudentRatio: "5.1:1",
    languageOfInstruction: "Español / Inglés",
    programDurationMonths: 48,
    class1Requirement: "Recomendado antes de iniciar vuelo.",
    jobSupportSummary: "Orientación dual académica y de vuelo con red limitada.",
    employmentClaimsType: "clear_non_guaranteed",
    scores: {
      documentTransparency: 58,
      costClarity: 49,
      financialRisk: 67,
      commercialRisk: 37,
      operationalSolidity: 60,
      dataConfidenceScore: 55,
    },
    redFlags: ["Coste de vuelo dependiente de condiciones externas."],
    pendingData: ["Escenarios de abandono de parte de vuelo.", "Detalle de prácticas con partner."],
    keyQuestions: ["¿Qué tramos académicos dependen de la parte de licencia?", "¿Qué licencias exactas se obtienen en cada hito?"],
    universityTrack: {
      universityName: "Universidad Piloto Madrid",
      degreeType: "Grado oficial",
      degreeName: "Grado en Gestión Aeronáutica y Formación de Vuelo",
      academicDurationYears: 4,
      ects: 240,
      licenseIncludedMode: "Parcial con cupos y fases",
      actualLicenseOutcome: "ATPL frozen sujeto a fases completadas",
      partnerAto: "Madrid Campus Flight Center",
      academicCostEUR: 45000,
      flightCostEUR: 76000,
      totalEstimatedCostEUR: 121000,
      class1FailurePolicy: "Puede continuar grado; itinerario de vuelo queda suspendido.",
    },
  },
];

