import type { SchoolEntry } from "@/types/schools";

// Primera tanda real/parcial para España (sin mezcla con dataset demo).
export const schoolsSpainDataset: SchoolEntry[] = [
  {
    // sourceUrl: https://usal.es/grado-en-piloto-de-aviacion-comercial-y-operaciones-aereas
    // sourceLabel: USAL - Grado oficial
    id: "es-adventia-usal",
    slug: "adventia-usal",
    name: "Adventia (European College of Aeronautics)",
    routeType: "university_plus_license",
    country: "España",
    city: "Salamanca",
    baseAirport: "Salamanca-Matacan",
    atoName: "Adventia",
    associatedUniversity: "Universidad de Salamanca",
    shortDescription: "Centro adscrito a USAL con grado en piloto comercial y operaciones aereas.",
    advertisedPriceEUR: 138219.18,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 48,
    depositOrEnrollmentFeeEUR: 500,
    paymentScheduleSummary: "Pago unico o fraccionado (45/35/20) segun PDF historico.",
    refundPolicySummary: "Reembolso de reserva/matricula del primer curso si no supera Class 1.",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "No publicado en fuentes revisadas.",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "espanol e ingles",
    class1Requirement: "Class 1 requerido antes de formalizar matricula.",
    jobSupportSummary: "No publicado de forma contractual en las fuentes revisadas.",
    employmentClaimsType: "unknown",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    dataConfidence: "low",
    dataStatus: "partial",
    lastUpdatedAt: "2026-05-06",
    redFlags: [
      "Precio publicado en PDF historico (2021/22), no necesariamente vigente.",
      "Condiciones contractuales incompletas en abierto.",
    ],
    pendingData: [
      "Precio vigente por convocatoria.",
      "Clausulas completas de cancelacion/reembolso.",
      "Detalle actualizado de incluidos/excluidos.",
    ],
    keyQuestions: [
      "Cual es el precio oficial 2026/27 completo y por anualidad?",
      "Existe contrato previo con politica de cancelacion detallada?",
      "Que costes no academicos quedan fuera?",
    ],
  },
  {
    // sourceUrl: https://europeanflyers.com/cursos-piloto-avion/curso-piloto-comercial-atpl
    // sourceLabel: Web oficial European Flyers
    id: "es-european-flyers",
    slug: "european-flyers",
    name: "European Flyers",
    routeType: "integrated",
    country: "España",
    city: "Madrid",
    baseAirport: "Madrid (Cuatro Vientos) / Alicante (Mutxamel)",
    atoName: "European Flyers",
    shortDescription:
      "ATO con integrado ATPL 180h y cursos modulares publicados en Madrid y Alicante.",
    advertisedPriceEUR: 85000,
    flypathEstimatedRealCostEUR: 89000,
    programDurationMonths: 24,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "Calendario de pagos no publicado.",
    refundPolicySummary: "No publicado.",
    contractAvailableBeforePayment: "yes",
    financingAvailable: "yes",
    mccJocIncluded: "yes",
    advancedUprtIncluded: "yes",
    examFeesIncluded: "yes",
    skillTestsIncluded: "yes",
    trainingMaterialsIncluded: "yes",
    accommodationIncluded: "optional",
    fleetSummary: "Cessna 172 G1000 y Diamond DA42 NG.",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "Español e inglés",
    class1Requirement: "Requerida para integrado y cursos profesionales; PPL requiere Clase 2.",
    jobSupportSummary:
      "Incluye preparacion para entrevistas y procesos de seleccion de aerolinea (sin garantia publicada).",
    employmentClaimsType: "clear_non_guaranteed",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 65,
    },
    dataConfidence: "medium",
    dataStatus: "partial",
    lastUpdatedAt: "2026-05-06",
    // Modular publicado (resumen): PPL, ATPL teorico, CPL, ME, ME&IR, MCC APS, UPRT, PBN y FI.
    // Precios publicados (web oficial): PPL 12.000; ATPL teorico 6.200; CPL 6.150; ME 5.000;
    // ME&IR 19.850; MCC APS 5.200; UPRT 1.450; PBN 575 (Madrid) / 450 (Alicante); FI 8.850.
    // Nota interna metodologica FlyPath:
    // Estimación FlyPath prudente basada en precio publicado e incluidos visibles;
    // pendiente de confirmar contrato, reintentos y condiciones de financiación.
    redFlags: [
      "Precio publicado con fecha de edición; confirmar vigencia antes de pagar.",
      "Calendario de pagos, depósito y política de reembolso no publicados.",
      "Confirmar por escrito el alcance exacto de MCC APS y skill tests incluidos.",
    ],
    pendingData: [],
    keyQuestions: [
      "¿El precio de 85.000 € sigue vigente para la convocatoria actual?",
      "¿Cuál es el calendario exacto de pagos y depósito?",
      "¿Se puede revisar el contrato completo antes de pagar?",
      "¿Qué ocurre si el alumno abandona o no supera una fase?",
    ],
  },
  {
    // sourceUrl: https://www.oneair.es/curso-piloto-comercial/
    // sourceLabel: One Air - CPL/ATPL programas y precios
    id: "es-one-air",
    slug: "one-air",
    name: "One Air Aviacion",
    routeType: "integrated",
    country: "España",
    city: "Malaga",
    baseAirport: "Malaga Internacional / La Axarquia",
    atoName: "One Air",
    shortDescription:
      "ATO en Malaga con varios itinerarios ATPL (integrated y modulares) y alta visibilidad comercial.",
    advertisedPriceEUR: 86500,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 24,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "Pagos aplazados al 0% (sin cronograma exacto publicado).",
    refundPolicySummary: "No publicado.",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "yes",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "optional",
    fleetSummary: "Mas de 30 aeronaves (Diamond, Cirrus, Tecnam) segun web.",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "bilingue (claim)",
    class1Requirement: "Class 1 requerido para acceso.",
    jobSupportSummary: "Preparacion de entrevistas y claim de garantia de trabajo por contrato.",
    employmentClaimsType: "guaranteed_claimed",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    dataConfidence: "low",
    dataStatus: "partial",
    lastUpdatedAt: "2026-05-06",
    redFlags: [
      "Parte de la informacion esta en formato comercial/promocional.",
      "No hay politica publica de reembolso/cancelacion en fuentes revisadas.",
    ],
    pendingData: [
      "Condiciones contractuales de garantia laboral.",
      "Calendario de pagos exacto por programa.",
      "Politicas de baja/cambios de precio.",
    ],
    keyQuestions: [
      "Que condiciones exactas tiene la garantia de trabajo?",
      "Que cargos adicionales pueden aparecer fuera del precio publicado?",
      "Se comparte contrato tipo previo a matricula?",
    ],
  },
  {
    // sourceUrl: https://easbcn.com/curso-de-piloto-de-avion-comercial/
    // sourceLabel: EAS - Curso integrado ATPL
    id: "es-eas-barcelona",
    slug: "eas-barcelona",
    name: "EAS Barcelona",
    routeType: "integrated",
    country: "España",
    city: "Barcelona",
    baseAirport: "Sabadell",
    atoName: "EAS Barcelona",
    shortDescription:
      "ATO en Barcelona/Sabadell con curso integrado ATPL y ruta modular teorica.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 16,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publica precio completo ni calendario de pagos.",
    refundPolicySummary: "No publicado.",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "optional",
    fleetSummary: "Aviones glass cockpit (sin listado completo publicado en pagina revisada).",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "Class 1 requerido para acceso.",
    jobSupportSummary: "Asesoramiento y preparacion para pruebas de seleccion tras licencia.",
    employmentClaimsType: "vague",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    dataConfidence: "low",
    dataStatus: "partial",
    lastUpdatedAt: "2026-05-06",
    redFlags: [
      "No publica precio oficial del integrado/modular en paginas revisadas.",
      "Reembolso/cancelacion no visible en abierto.",
    ],
    pendingData: ["Precio y plazos de pago.", "Clausulas de devolucion/cancelacion."],
    keyQuestions: [
      "Precio vigente de integrado y modular?",
      "Hay politica de reembolso previa a firma?",
      "Que gastos quedan fuera del paquete incluido?",
    ],
  },
  {
    // sourceUrl: https://barcelonaflightschool.com/pilot-training/integrated-airline-transport-pilot-atpl-fast-track-course/
    // sourceLabel: BFS - Integrated ATPL
    id: "es-barcelona-flight-school",
    slug: "barcelona-flight-school",
    name: "Barcelona Flight School",
    routeType: "integrated",
    country: "España",
    city: "Sabadell",
    baseAirport: "Sabadell",
    atoName: "Barcelona Flight School",
    shortDescription:
      "ATO en Sabadell con programa integrated ATPL fast track y oferta modular complementaria.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 24,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publica precio completo ni calendario de pagos.",
    refundPolicySummary: "No publicado.",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Entrenamiento sobre C152/P92, C172R-S, P2006T y simuladores asociados.",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "Class 1 requerido para acceso.",
    jobSupportSummary: "Preparacion para entrevistas de aerolinea (sin garantia formal publicada).",
    employmentClaimsType: "vague",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    dataConfidence: "low",
    dataStatus: "partial",
    lastUpdatedAt: "2026-05-06",
    redFlags: [
      "Precio no publicado en pagina oficial revisada.",
      "Condiciones de baja/reembolso no publicadas en abierto.",
    ],
    pendingData: ["Precio por programa.", "Contrato y clausulas de cancelacion/reembolso."],
    keyQuestions: [
      "Precio oficial 2026 de integrado/modular?",
      "Contrato tipo disponible antes de reserva?",
      "Que costes adicionales quedan fuera del curso base?",
    ],
  },
  {
    // sourceUrl: https://www.cesda.com/grado-piloto/presentacion
    // sourceLabel: CESDA - Presentacion grado
    id: "es-cesda-urv",
    slug: "cesda-urv",
    name: "CESDA / Universitat Rovira i Virgili",
    routeType: "university_plus_license",
    country: "España",
    city: "Reus",
    baseAirport: "Reus",
    atoName: "CESDA",
    associatedUniversity: "Universitat Rovira i Virgili",
    shortDescription:
      "Ruta universitaria con grado oficial y licencia EASA hasta ATPL frozen en entorno CESDA/URV.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 48,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "Fraccionamiento anual hasta 9 cuotas sin intereses.",
    refundPolicySummary: "No publicado en detalle en paginas revisadas.",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "yes",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "No publicado en detalle en paginas revisadas.",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado de forma explicita en paginas revisadas.",
    jobSupportSummary: "Claims de alta insercion y red de contactos en el sector.",
    employmentClaimsType: "vague",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    dataConfidence: "low",
    dataStatus: "partial",
    lastUpdatedAt: "2026-05-06",
    redFlags: [
      "Precio exacto no visible en pagina principal (remite a dossier).",
      "Normativa/reembolso no extraida aun del PDF completo.",
    ],
    pendingData: [
      "Precio oficial detallado 2026/27.",
      "Clausulas de reembolso/cancelacion.",
      "Costes externos a matricula.",
    ],
    keyQuestions: [
      "Precio total y por curso vigente?",
      "Politica de devolucion tras matricula?",
      "Que costes externos debe prever el alumno?",
    ],
  },
  {
    // sourceUrl: https://www.ftejerez.com
    // sourceLabel: Web oficial
    id: "es-fte-jerez",
    slug: "fte-jerez",
    name: "FTE Jerez",
    routeType: "integrated",
    country: "España",
    city: "Jerez de la Frontera",
    baseAirport: "Jerez",
    atoName: "FTE Jerez",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.qualityfly.com
    // sourceLabel: Web oficial
    id: "es-quality-fly",
    slug: "quality-fly",
    name: "Quality Fly",
    routeType: "integrated",
    country: "España",
    city: "Madrid",
    baseAirport: "Cuatro Vientos",
    atoName: "Quality Fly",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.flybyschool.com
    // sourceLabel: Web oficial
    id: "es-flyby-aviation-academy",
    slug: "flyby-aviation-academy",
    name: "FlyBy Aviation Academy",
    routeType: "integrated",
    country: "España",
    city: "Burgos",
    baseAirport: "Burgos",
    atoName: "FlyBy Aviation Academy",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.canavia.it/es/canavia-flight-school-canary-islands
    // sourceLabel: Web oficial
    id: "es-canavia-flight-school",
    slug: "canavia-flight-school",
    name: "Canavia Flight School",
    routeType: "integrated",
    country: "España",
    city: "Gran Canaria / Tenerife",
    baseAirport: "GCLP / bases Canarias",
    atoName: "Canavia Flight School",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://corflightschool.com
    // sourceLabel: Web oficial
    id: "es-corflight-school",
    slug: "corflight-school",
    name: "Corflight School",
    routeType: "integrated",
    country: "España",
    city: "Madrid",
    baseAirport: "Cuatro Vientos",
    atoName: "Corflight School",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.flyschool.es
    // sourceLabel: Web oficial
    id: "es-flyschool-air-academy",
    slug: "flyschool-air-academy",
    name: "Flyschool Air Academy",
    routeType: "integrated",
    country: "España",
    city: "Madrid / Mallorca",
    baseAirport: "Cuatro Vientos / Son Bonet",
    atoName: "Flyschool Air Academy",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://airpullaviationacademy.com
    // sourceLabel: Web oficial
    id: "es-airpull-aviation-academy",
    slug: "airpull-aviation-academy",
    name: "Airpull Aviation Academy",
    routeType: "integrated",
    country: "España",
    city: "Requena (Valencia)",
    baseAirport: "Requena (LERE)",
    atoName: "Airpull Aviation Academy",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://worldaviationato.com
    // sourceLabel: Web oficial
    id: "es-world-aviation-ato",
    slug: "world-aviation-ato",
    name: "World Aviation ATO",
    routeType: "modular",
    country: "España",
    city: "Málaga / Madrid",
    baseAirport: "Málaga / Cuatro Vientos",
    atoName: "World Aviation ATO",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.aerotec.es
    // sourceLabel: Web oficial
    id: "es-aerotec",
    slug: "aerotec",
    name: "AEROTEC Escuela de Pilotos",
    routeType: "integrated",
    country: "España",
    city: "Madrid / Sevilla / Palma",
    baseAirport: "Cuatro Vientos / Sevilla / Son Bonet",
    atoName: "AEROTEC",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.aerodynamics.es
    // sourceLabel: Web oficial
    id: "es-aerodynamics-academy",
    slug: "aerodynamics-academy",
    name: "Aerodynamics Academy",
    routeType: "integrated",
    country: "España",
    city: "Málaga / Granada / Madrid",
    baseAirport: "Vélez-Málaga (principal)",
    atoName: "Aerodynamics Academy",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://panamedia.org
    // sourceLabel: Web oficial
    id: "es-panamedia-escuela-de-pilotos",
    slug: "panamedia-escuela-de-pilotos",
    name: "Panamedia Escuela de Pilotos",
    routeType: "integrated",
    country: "España",
    city: "Manises (Valencia) / Mallorca",
    baseAirport: "Valencia-Manises / Son Bonet",
    atoName: "Panamedia",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://aerolink.es/en/
    // sourceLabel: Web oficial
    id: "es-aero-link-flight-academy",
    slug: "aero-link-flight-academy",
    name: "Aero Link Flight Academy",
    routeType: "integrated",
    country: "España",
    city: "Sabadell",
    baseAirport: "Sabadell",
    atoName: "Aero Link Flight Academy",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://aerotablada.com/formacion/
    // sourceLabel: Web oficial
    id: "es-aerotablada",
    slug: "aerotablada",
    name: "Aerotablada",
    routeType: "modular",
    country: "España",
    city: "Sevilla",
    baseAirport: "Sevilla / Bollullos",
    atoName: "Aerotablada",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: http://www.aero2mil.es/
    // sourceLabel: Web oficial
    id: "es-aero2mil",
    slug: "aero2mil",
    name: "Aero2mil",
    routeType: "modular",
    country: "España",
    city: "Sevilla",
    baseAirport: "Bollullos",
    atoName: "Aero2mil",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.lecuaviation.com/nuestra-escuela
    // sourceLabel: Web oficial
    id: "es-lecu-aviation",
    slug: "lecu-aviation",
    name: "LECU Aviation",
    routeType: "modular",
    country: "España",
    city: "Madrid",
    baseAirport: "Cuatro Vientos",
    atoName: "LECU Aviation",
    shortDescription: "Entidad incluida en índice amplio; datos pendientes de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.aeroclub.es/
    // sourceLabel: Web oficial
    id: "es-aeroclub-barcelona-sabadell",
    slug: "aeroclub-barcelona-sabadell",
    name: "L'Aeroclub Barcelona-Sabadell",
    routeType: "modular",
    country: "España",
    city: "Sabadell",
    baseAirport: "Sabadell",
    atoName: "L'Aeroclub Barcelona-Sabadell",
    shortDescription: "Aeroclub incluido en índice amplio; información pendiente de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://realaeroclubgrancanaria.es/
    // sourceLabel: Web oficial
    id: "es-real-aeroclub-gran-canaria",
    slug: "real-aeroclub-gran-canaria",
    name: "Real Aeroclub de Gran Canaria",
    routeType: "modular",
    country: "España",
    city: "San Bartolomé de Tirajana",
    baseAirport: "El Berriel (GCLB)",
    atoName: "Real Aeroclub de Gran Canaria",
    shortDescription: "Aeroclub incluido en índice amplio; información pendiente de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: http://www.realaeroclubdezaragoza.com/
    // sourceLabel: Web oficial
    id: "es-real-aero-club-zaragoza",
    slug: "real-aero-club-zaragoza",
    name: "Real Aero Club de Zaragoza",
    routeType: "modular",
    country: "España",
    city: "Zaragoza",
    baseAirport: "Aeropuerto de Zaragoza",
    atoName: "Real Aero Club de Zaragoza",
    shortDescription: "Aeroclub incluido en índice amplio; información pendiente de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://usal.es/grado-en-piloto-de-aviacion-comercial-y-operaciones-aereas
    // sourceLabel: Web oficial
    id: "es-universidad-salamanca-grado-piloto",
    slug: "universidad-salamanca-grado-piloto",
    name: "Universidad de Salamanca (Grado Piloto)",
    routeType: "university_plus_license",
    country: "España",
    city: "Salamanca",
    baseAirport: "Matacán",
    atoName: "Universidad de Salamanca",
    associatedUniversity: "Universidad de Salamanca",
    shortDescription: "Universidad incluida en índice amplio; información pendiente de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.uam.es/uam/gestion-aeronautica
    // sourceLabel: Web oficial
    id: "es-uam-gestion-aeronautica",
    slug: "uam-gestion-aeronautica",
    name: "UAM - Grado en Gestión Aeronáutica",
    routeType: "university_plus_license",
    country: "España",
    city: "Madrid",
    baseAirport: "No publicado",
    atoName: "UAM",
    associatedUniversity: "Universidad Autónoma de Madrid",
    shortDescription: "Universidad incluida en índice amplio; información pendiente de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.uab.cat/web/estudiar/listado-de-grados/informacion-general/gestion-aeronautica-1216708258897.html
    // sourceLabel: Web oficial
    id: "es-uab-gestion-aeronautica",
    slug: "uab-gestion-aeronautica",
    name: "UAB - Grado en Gestión Aeronáutica",
    routeType: "university_plus_license",
    country: "España",
    city: "Sabadell (Barcelona)",
    baseAirport: "No publicado",
    atoName: "UAB",
    associatedUniversity: "Universitat Autònoma de Barcelona",
    shortDescription: "Universidad incluida en índice amplio; información pendiente de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // sourceUrl: https://www.upm.es
    // sourceLabel: Web oficial
    id: "es-upm-gestion-operaciones-transporte-aereo",
    slug: "upm-gestion-operaciones-transporte-aereo",
    name: "UPM - Grado en Gestión y Operaciones del Transporte Aéreo",
    routeType: "university_plus_license",
    country: "España",
    city: "Madrid",
    baseAirport: "No publicado",
    atoName: "UPM",
    associatedUniversity: "Universidad Politécnica de Madrid",
    shortDescription: "Universidad incluida en índice amplio; información pendiente de confirmación detallada.",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    programDurationMonths: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    studentAircraftRatio: "",
    instructorStudentRatio: "",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: { documentTransparency: 0, costClarity: 0, financialRisk: 0, commercialRisk: 0, operationalSolidity: 0, dataConfidenceScore: 0 },
    dataConfidence: "low",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    redFlags: ["Información pendiente de confirmar."],
    pendingData: ["Precio publicado", "Incluidos y excluidos", "Contrato antes de pagar", "Política de reembolso", "Calendario de pagos"],
    keyQuestions: ["¿Cuál es el precio total actualizado?", "¿Qué conceptos están incluidos y cuáles quedan fuera?", "¿Existe contrato y política de reembolso antes de pagar?", "¿Cuál es el calendario de pagos?"],
  },
  {
    // AESA ATO: E-ATO-047
    id: "es-aeroflota-del-noroeste-afn",
    slug: "aeroflota-del-noroeste-afn",
    name: "Aeroflota del Noroeste (AFN)",
    routeType: "modular",
    country: "España",
    city: "Culleredo (A Coruña)",
    baseAirport: "Aeropuerto de Alvedro",
    atoName: "AEROFLOTA DEL NOROESTE, S.L.",
    shortDescription:
      "Entidad ATO oficial AESA con datos economicos y contractuales pendientes de confirmacion publica.",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    dataConfidence: "low",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    programDurationMonths: 0,
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    redFlags: ["Información pendiente de confirmar."],
    pendingData: [
      "Precio publicado",
      "Incluidos y excluidos",
      "Contrato antes de pagar",
      "Política de reembolso",
      "Calendario de pagos",
    ],
    keyQuestions: [
      "¿Cuál es el precio total actualizado?",
      "¿Qué conceptos están incluidos y cuáles quedan fuera?",
      "¿Existe contrato y política de reembolso antes de pagar?",
      "¿Cuál es el calendario de pagos?",
    ],
  },
  {
    // AESA ATO: E-ATO-286
    id: "es-dreamair-flight-school",
    slug: "dreamair-flight-school",
    name: "DreamAir Flight School",
    routeType: "modular",
    country: "España",
    city: "Barcelona",
    baseAirport: "Pendiente de confirmar",
    atoName: "DREAMAIRFLIGHTSCHOOL, S.L.",
    shortDescription:
      "Escuela listada en AESA como ATO; posible foco en formacion inicial, con datos economicos pendientes.",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    dataConfidence: "low",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    programDurationMonths: 0,
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    redFlags: ["Información pendiente de confirmar."],
    pendingData: [
      "Precio publicado",
      "Incluidos y excluidos",
      "Contrato antes de pagar",
      "Política de reembolso",
      "Calendario de pagos",
    ],
    keyQuestions: [
      "¿Cuál es el precio total actualizado?",
      "¿Qué conceptos están incluidos y cuáles quedan fuera?",
      "¿Existe contrato y política de reembolso antes de pagar?",
      "¿Cuál es el calendario de pagos?",
    ],
  },
  {
    // AESA ATO: E-ATO-010
    id: "es-real-aero-club-sevilla",
    slug: "real-aero-club-sevilla",
    name: "Real Aero Club de Sevilla",
    routeType: "modular",
    country: "España",
    city: "Sevilla",
    baseAirport: "Aeropuerto de Sevilla",
    atoName: "REAL AERO CLUB DE SEVILLA",
    shortDescription:
      "Aeroclub ATO oficial en AESA con posible foco PPL; ruta exacta y alcance pendientes de confirmar.",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    dataConfidence: "low",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    programDurationMonths: 0,
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    redFlags: ["Información pendiente de confirmar."],
    pendingData: [
      "Precio publicado",
      "Incluidos y excluidos",
      "Contrato antes de pagar",
      "Política de reembolso",
      "Calendario de pagos",
    ],
    keyQuestions: [
      "¿Cuál es el precio total actualizado?",
      "¿Qué conceptos están incluidos y cuáles quedan fuera?",
      "¿Existe contrato y política de reembolso antes de pagar?",
      "¿Cuál es el calendario de pagos?",
    ],
  },
  {
    // AESA ATO: E-ATO-070
    id: "es-real-aeroclub-alicante",
    slug: "real-aeroclub-alicante",
    name: "Real Aeroclub de Alicante",
    routeType: "modular",
    country: "España",
    city: "Mutxamel (Alicante)",
    baseAirport: "Mutxamel",
    atoName: "REAL AEROCLUB DE ALICANTE",
    shortDescription:
      "Aeroclub ATO oficial AESA con informacion publica de costes y condiciones aun pendiente de confirmar.",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    dataConfidence: "low",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    programDurationMonths: 0,
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    redFlags: ["Información pendiente de confirmar."],
    pendingData: [
      "Precio publicado",
      "Incluidos y excluidos",
      "Contrato antes de pagar",
      "Política de reembolso",
      "Calendario de pagos",
    ],
    keyQuestions: [
      "¿Cuál es el precio total actualizado?",
      "¿Qué conceptos están incluidos y cuáles quedan fuera?",
      "¿Existe contrato y política de reembolso antes de pagar?",
      "¿Cuál es el calendario de pagos?",
    ],
  },
  {
    // AESA ATO: E-ATO-065
    id: "es-real-aeroclub-navarra",
    slug: "real-aeroclub-navarra",
    name: "Real Aeroclub de Navarra",
    routeType: "modular",
    country: "España",
    city: "Noain (Navarra)",
    baseAirport: "Pamplona-Noain",
    atoName: "REAL AEROCLUB DE NAVARRA",
    shortDescription:
      "Aeroclub ATO oficial en AESA relevante para formacion inicial, con detalle economico pendiente.",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    dataConfidence: "low",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    programDurationMonths: 0,
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    redFlags: ["Información pendiente de confirmar."],
    pendingData: [
      "Precio publicado",
      "Incluidos y excluidos",
      "Contrato antes de pagar",
      "Política de reembolso",
      "Calendario de pagos",
    ],
    keyQuestions: [
      "¿Cuál es el precio total actualizado?",
      "¿Qué conceptos están incluidos y cuáles quedan fuera?",
      "¿Existe contrato y política de reembolso antes de pagar?",
      "¿Cuál es el calendario de pagos?",
    ],
  },
  {
    // AESA ATO: E-ATO-066
    id: "es-aeroclub-vitoria-heraclio-alfaro",
    slug: "aeroclub-vitoria-heraclio-alfaro",
    name: "Aeroclub de Vitoria Heraclio Alfaro",
    routeType: "modular",
    country: "España",
    city: "Foronda (Vitoria-Gasteiz)",
    baseAirport: "Aeropuerto de Vitoria-Gasteiz",
    atoName: "AEROCLUB DE VITORIA HERACLIO ALFARO",
    shortDescription:
      "Aeroclub en listado oficial AESA ATO, con informacion operativa y economica pendiente de confirmar.",
    dataStatus: "unknown",
    lastUpdatedAt: "2026-05-06",
    dataConfidence: "low",
    advertisedPriceEUR: 0,
    flypathEstimatedRealCostEUR: 0,
    depositOrEnrollmentFeeEUR: 0,
    paymentScheduleSummary: "No publicado",
    refundPolicySummary: "No publicado",
    contractAvailableBeforePayment: "unknown",
    financingAvailable: "unknown",
    mccJocIncluded: "unknown",
    advancedUprtIncluded: "unknown",
    examFeesIncluded: "unknown",
    skillTestsIncluded: "unknown",
    trainingMaterialsIncluded: "unknown",
    accommodationIncluded: "unknown",
    fleetSummary: "Pendiente de confirmar",
    aircraftAvailability: "unknown",
    languageOfInstruction: "No publicado",
    programDurationMonths: 0,
    class1Requirement: "No publicado",
    jobSupportSummary: "No publicado",
    employmentClaimsType: "unknown",
    scores: {
      documentTransparency: 0,
      costClarity: 0,
      financialRisk: 0,
      commercialRisk: 0,
      operationalSolidity: 0,
      dataConfidenceScore: 0,
    },
    redFlags: ["Información pendiente de confirmar."],
    pendingData: [
      "Precio publicado",
      "Incluidos y excluidos",
      "Contrato antes de pagar",
      "Política de reembolso",
      "Calendario de pagos",
    ],
    keyQuestions: [
      "¿Cuál es el precio total actualizado?",
      "¿Qué conceptos están incluidos y cuáles quedan fuera?",
      "¿Existe contrato y política de reembolso antes de pagar?",
      "¿Cuál es el calendario de pagos?",
    ],
  },
];
